### ISSUE TITLE
Use Ruby on Rails encrypted credentials instead of git-crypt

### ISSUE THREAD

**Issue by ghost** [civica-digital/rails-templates#4]
Cons:
- Only works with Ruby on Rails 5.2
- Nongranular access
- No Heroku support
- We need to teach clients how to use Rails credentials

Pros:
- No need to manage an asynchronous PGP key pair
- Part of the "convention" instead of "configuration"
- Credentials would be embedded in the image (one deploy / containerized)

**Comment by fercreek** [comment]
@mroutis  I think that it's okay if we are working with other devs. For the service team, I would use Heroku instead AWS for the first months.

**Comment by ghost** [comment]
Closing for lack of interest
